### ISSUE TITLE
How to generate 3d meshes from the real inverted image

### ISSUE THREAD

**Issue by minar09** [oneThousand1000/EG3D-projector#18]
Hi, thanks for the impressive work. I found that you are generating videos from the pre-generated network pickle and latent code from the inverted inputs. Is there a way to just save the 3D mesh with or without texture in .ply/.mrc/.obj format for the custom latent code? Maybe some changes around here https://github.com/oneThousand1000/EG3D-projector/blob/a9c61920b5f127a2c9eba68cab7b7fc7bacf9274/eg3d/gen_samples.py#L199 ? Any help will be highly appreciated. Thank you.

**Comment by oneThousand1000** [comment]
Hi, you should make the following modifications:
1. Write a new sample function at https://github.com/oneThousand1000/EG3D-projector/blob/a9c61920b5f127a2c9eba68cab7b7fc7bacf9274/eg3d/training/triplane.py#L91 like:
```
    def sample_ws(self, coordinates, directions, ws c, truncation_psi=1, truncation_cutoff=None, update_emas=False, **synthesis_kwargs):
        planes = self.backbone.synthesis(ws, update_emas=update_emas, **synthesis_kwargs)
        planes = planes.view(len(planes), 3, 32, planes.shape[-2], planes.shape[-1])
        return self.renderer.run_model(planes, self.decoder, coordinates, directions, self.rendering_kwargs)
```
2. Make sure you reload the model so that the above modification could work (https://github.com/oneThousand1000/EG3D-projector/blob/a9c61920b5f127a2c9eba68cab7b7fc7bacf9274/eg3d/gen_samples.py#L146).
3. Use G.sample_ws to sample sigma,  where the input ws code is the inversion latent code.

**Comment by minar09** [comment]
Thank you very much @oneThousand1000 for your quick response. It worked nicely. Please pardon my additional question. Is there a way to generate the textured mesh as well? Really appreciate your help. Thank you.

**Comment by oneThousand1000** [comment]
> Thank you very much @oneThousand1000 for your quick response. It worked nicely. Please pardon my additional question. Is there a way to generate the textured mesh as well? Really appreciate your help. Thank you.

It may take some effort. If you get the texture by directly projecting the pixels of the real image to the 3d mesh, there exist invisible area. Please refer to https://github.com/jiaxinxie97/HFGI3D to see how to inpaint the invisible area.

**Comment by minar09** [comment]
Thank you very much again for your answer.
